"""initial

Revision ID: ffd2288315fa
Revises: 
Create Date: 2024-08-26 15:43:37.970927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd2288315fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Charity',
    sa.Column('CharityId', sa.Integer(), nullable=False),
    sa.Column('CharityName', sa.String(), nullable=True),
    sa.Column('CharityDescription', sa.String(), nullable=True),
    sa.Column('CharityLogo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CharityId')
    )
    op.create_table('Country',
    sa.Column('CountryCode', sa.String(), nullable=False),
    sa.Column('CountryName', sa.String(), nullable=True),
    sa.Column('CountryFlag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('CountryCode')
    )
    op.create_table('EventType',
    sa.Column('EventTypeId', sa.Integer(), nullable=False),
    sa.Column('EventTypeName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EventTypeId')
    )
    op.create_table('Gender',
    sa.Column('Gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Gender')
    )
    op.create_table('Position',
    sa.Column('PositionId', sa.Integer(), nullable=False),
    sa.Column('PositionName', sa.String(), nullable=True),
    sa.Column('PositionDescription', sa.String(), nullable=True),
    sa.Column('PayPeriod', sa.String(), nullable=True),
    sa.Column('PayRate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('PositionId')
    )
    op.create_table('RaceKitOption',
    sa.Column('RaceKitOptionId', sa.Integer(), nullable=False),
    sa.Column('RaceKitOption', sa.String(), nullable=True),
    sa.Column('Cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('RaceKitOptionId')
    )
    op.create_table('RegistrationStatus',
    sa.Column('RegistrationStatusId', sa.Integer(), nullable=False),
    sa.Column('RegistrationStatus', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('RegistrationStatusId')
    )
    op.create_table('Role',
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('RoleId')
    )
    op.create_table('Marathon',
    sa.Column('MarathonId', sa.Integer(), nullable=False),
    sa.Column('MarathonName', sa.String(), nullable=True),
    sa.Column('CityName', sa.String(), nullable=True),
    sa.Column('CountryCode', sa.String(), nullable=True),
    sa.Column('YearHeld', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CountryCode'], ['Country.CountryCode'], ),
    sa.PrimaryKeyConstraint('MarathonId')
    )
    op.create_table('Staff',
    sa.Column('StaffId', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('LastName', sa.String(), nullable=True),
    sa.Column('DateOfBirth', sa.DateTime(), nullable=True),
    sa.Column('Gender', sa.String(), nullable=True),
    sa.Column('PositionId', sa.Integer(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Gender'], ['Gender.Gender'], ),
    sa.ForeignKeyConstraint(['PositionId'], ['Position.PositionId'], ),
    sa.PrimaryKeyConstraint('StaffId')
    )
    op.create_table('User',
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=True),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('LastName', sa.String(), nullable=True),
    sa.Column('RoleId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RoleId'], ['Role.RoleId'], ),
    sa.PrimaryKeyConstraint('Email')
    )
    op.create_table('Volunteer',
    sa.Column('VolunteerId', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('LastName', sa.String(), nullable=True),
    sa.Column('CountryCode', sa.String(), nullable=True),
    sa.Column('Gender', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CountryCode'], ['Country.CountryCode'], ),
    sa.ForeignKeyConstraint(['Gender'], ['Gender.Gender'], ),
    sa.PrimaryKeyConstraint('VolunteerId')
    )
    op.create_table('Event',
    sa.Column('EventId', sa.Integer(), nullable=False),
    sa.Column('EventName', sa.String(), nullable=True),
    sa.Column('EventTypeId', sa.Integer(), nullable=True),
    sa.Column('MarathonId', sa.Integer(), nullable=True),
    sa.Column('StartDateTime', sa.DateTime(), nullable=True),
    sa.Column('Cost', sa.Float(), nullable=True),
    sa.Column('MaxParticipants', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EventTypeId'], ['EventType.EventTypeId'], ),
    sa.ForeignKeyConstraint(['MarathonId'], ['Marathon.MarathonId'], ),
    sa.PrimaryKeyConstraint('EventId')
    )
    op.create_table('Runner',
    sa.Column('RunnerId', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Gender', sa.String(), nullable=True),
    sa.Column('DateOfBirth', sa.DateTime(), nullable=True),
    sa.Column('CountryCode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CountryCode'], ['Country.CountryCode'], ),
    sa.ForeignKeyConstraint(['Email'], ['User.Email'], ),
    sa.ForeignKeyConstraint(['Gender'], ['Gender.Gender'], ),
    sa.PrimaryKeyConstraint('RunnerId')
    )
    op.create_table('Timesheet',
    sa.Column('TimesheetId', sa.Integer(), nullable=False),
    sa.Column('StaffId', sa.Integer(), nullable=True),
    sa.Column('StartDateTime', sa.DateTime(), nullable=True),
    sa.Column('EndDateTime', sa.DateTime(), nullable=True),
    sa.Column('PayAmount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['StaffId'], ['Staff.StaffId'], ),
    sa.PrimaryKeyConstraint('TimesheetId')
    )
    op.create_table('Registration',
    sa.Column('RegistrationId', sa.Integer(), nullable=False),
    sa.Column('RunnerId', sa.Integer(), nullable=True),
    sa.Column('RegistrationDateTime', sa.DateTime(), nullable=True),
    sa.Column('RaceKitOptionId', sa.Integer(), nullable=True),
    sa.Column('RegistrationStatusId', sa.Integer(), nullable=True),
    sa.Column('Cost', sa.Float(), nullable=True),
    sa.Column('CharityId', sa.Integer(), nullable=True),
    sa.Column('SponsorshipTarget', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['CharityId'], ['Charity.CharityId'], ),
    sa.ForeignKeyConstraint(['RaceKitOptionId'], ['RaceKitOption.RaceKitOptionId'], ),
    sa.ForeignKeyConstraint(['RegistrationStatusId'], ['RegistrationStatus.RegistrationStatusId'], ),
    sa.ForeignKeyConstraint(['RunnerId'], ['Runner.RunnerId'], ),
    sa.PrimaryKeyConstraint('RegistrationId')
    )
    op.create_table('Registration_Event',
    sa.Column('RegistrationEventId', sa.Integer(), nullable=False),
    sa.Column('RegistrationId', sa.Integer(), nullable=True),
    sa.Column('EventId', sa.Integer(), nullable=True),
    sa.Column('BibNumber', sa.Integer(), nullable=True),
    sa.Column('RaceTime', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['EventId'], ['Event.EventId'], ),
    sa.ForeignKeyConstraint(['RegistrationId'], ['Registration.RegistrationId'], ),
    sa.PrimaryKeyConstraint('RegistrationEventId')
    )
    op.create_table('Sponsorship',
    sa.Column('SponsorshipId', sa.Integer(), nullable=False),
    sa.Column('SponsorName', sa.String(), nullable=True),
    sa.Column('RegistrationId', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['RegistrationId'], ['Registration.RegistrationId'], ),
    sa.PrimaryKeyConstraint('SponsorshipId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sponsorship')
    op.drop_table('Registration_Event')
    op.drop_table('Registration')
    op.drop_table('Timesheet')
    op.drop_table('Runner')
    op.drop_table('Event')
    op.drop_table('Volunteer')
    op.drop_table('User')
    op.drop_table('Staff')
    op.drop_table('Marathon')
    op.drop_table('Role')
    op.drop_table('RegistrationStatus')
    op.drop_table('RaceKitOption')
    op.drop_table('Position')
    op.drop_table('Gender')
    op.drop_table('EventType')
    op.drop_table('Country')
    op.drop_table('Charity')
    # ### end Alembic commands ###
