# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\сonfirmation_of_sponsorship.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "QFrame#frame_bg{\n"
            "    background-color: rgb(255, 255, 255);\n"
            "}\n"
            "QFrame{\n"
            "    color: rgb(125, 125, 125);\n"
            "}\n"
            "QLabel#heading{\n"
            "    font-size: 24pt;\n"
            "    color: rgb(255, 255, 255);\n"
            "    background-color: rgb(82, 82, 82);\n"
            "}\n"
            "QLabel#bottom{\n"
            "    font-size: 14pt;\n"
            "    color: rgb(204, 204, 204);\n"
            "    background-color: rgb(82, 82, 82);\n"
            "}\n"
            "QPushButton {\n"
            "    background-color: rgb(242, 242, 242);\n"
            "    border: 2px solid;\n"
            "    border-radius: 10px;\n"
            "    border-color: rgb(140, 140, 140);\n"
            "}\n"
            "QComboBox{\n"
            "    color: rgb(125, 125, 125);\n"
            "}\n"
            "QDateEdit{\n"
            "    color: rgb(125, 125, 125);\n"
            "}"
        )
        self.centralwidget.setObjectName("centralwidget")
        self.frame_bg = QtWidgets.QFrame(self.centralwidget)
        self.frame_bg.setGeometry(QtCore.QRect(0, 0, 811, 561))
        self.frame_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg.setObjectName("frame_bg")
        self.pushButton = QtWidgets.QPushButton(self.frame_bg)
        self.pushButton.setGeometry(QtCore.QRect(370, 440, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.heading = QtWidgets.QLabel(self.frame_bg)
        self.heading.setGeometry(QtCore.QRect(0, 0, 801, 61))
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName("heading")
        self.bottom = QtWidgets.QLabel(self.frame_bg)
        self.bottom.setGeometry(QtCore.QRect(0, 500, 801, 61))
        self.bottom.setAlignment(QtCore.Qt.AlignCenter)
        self.bottom.setObjectName("bottom")
        self.label = QtWidgets.QLabel(self.frame_bg)
        self.label.setGeometry(QtCore.QRect(150, 70, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_bg)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 681, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_bg)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.frame_bg)
        self.label_3.setGeometry(QtCore.QRect(70, 160, 681, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_bg)
        self.label_4.setGeometry(QtCore.QRect(80, 210, 681, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_bg)
        self.label_5.setGeometry(QtCore.QRect(80, 300, 681, 101))
        font = QtGui.QFont()
        font.setPointSize(71)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.heading.raise_()
        self.bottom.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Назад"))
        self.heading.setText(_translate("MainWindow", "MARATHON SKILLS 2024"))
        self.bottom.setText(
            _translate("MainWindow", "18 дней 8 часов и 17 минут до старта марафона")
        )
        self.label.setText(
            _translate("MainWindow", "Спасибо за вашу спонсорскую поддержку!")
        )
        self.label_2.setText(
            _translate(
                "MainWindow",
                "Спасибо за поддержку бегуна в Marathon Skills 2016!\n"
                " Ваше пожертвование пойдет в его благотворительную организацию",
            )
        )
        self.pushButton_2.setText(_translate("MainWindow", "Назад"))
        self.label_3.setText(_translate("MainWindow", "Иван Прудов(204) из Russia"))
        self.label_4.setText(_translate("MainWindow", "Фонд кошек"))
        self.label_5.setText(_translate("MainWindow", "$50"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
