# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'greet.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiGreetWindow(object):

    def setupUi(self, UiGreetWindow):
        UiGreetWindow.setObjectName("UiGreetWindow")
        UiGreetWindow.resize(789, 610)
        self.centralwidget = QtWidgets.QWidget(UiGreetWindow)
        self.centralwidget.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(242, 242, 242);\n"
            "    border: 2px solid;\n"
            "    border-radius: 10px;\n"
            "    border-color: rgb(140, 140, 140);\n"
            "}\n"
            "\n"
            "QFrame {\n"
            "    background-color: rgb(82, 82, 82);\n"
            "}\n"
            "\n"
            "QLabel#greet_heading{\n"
            "    font-size: 24pt;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "\n"
            "QLabel#greet_city_label, QLabel#greet_date_label{\n"
            "    font-size: 14pt;\n"
            "    color: rgb(204, 204, 204);\n"
            "}\n"
            "\n"
            "QLabel#greet_time_left{\n"
            "    font-size: 12pt;\n"
            "    color: #fff;\n"
            "}\n"
            "\n"
            "QFrame#greet_bg{\n"
            "    background-color: rgb(255, 255, 255);\n"
            "}"
        )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_head = QtWidgets.QFrame(self.centralwidget)
        self.frame_head.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_head.setStyleSheet("")
        self.frame_head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_head.setObjectName("frame_head")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_head)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(24)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.greet_heading = QtWidgets.QLabel(self.frame_head)
        self.greet_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.greet_heading.setObjectName("greet_heading")
        self.verticalLayout_3.addWidget(self.greet_heading)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.greet_city_label = QtWidgets.QLabel(self.frame_head)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.greet_city_label.sizePolicy().hasHeightForWidth()
        )
        self.greet_city_label.setSizePolicy(sizePolicy)
        self.greet_city_label.setMinimumSize(QtCore.QSize(0, 40))
        self.greet_city_label.setAlignment(QtCore.Qt.AlignCenter)
        self.greet_city_label.setObjectName("greet_city_label")
        self.verticalLayout_2.addWidget(self.greet_city_label)
        self.greet_date_label = QtWidgets.QLabel(self.frame_head)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.greet_date_label.sizePolicy().hasHeightForWidth()
        )
        self.greet_date_label.setSizePolicy(sizePolicy)
        self.greet_date_label.setMinimumSize(QtCore.QSize(0, 40))
        self.greet_date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.greet_date_label.setObjectName("greet_date_label")
        self.verticalLayout_2.addWidget(self.greet_date_label)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addWidget(self.frame_head)
        self.greet_bg = QtWidgets.QFrame(self.centralwidget)
        self.greet_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.greet_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.greet_bg.setObjectName("greet_bg")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.greet_bg)
        self.verticalLayout_6.setContentsMargins(0, 50, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.want_run_btn = QtWidgets.QPushButton(self.greet_bg)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(self.want_run_btn.sizePolicy().hasHeightForWidth())
        self.want_run_btn.setSizePolicy(sizePolicy)
        self.want_run_btn.setMinimumSize(QtCore.QSize(300, 60))
        self.want_run_btn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.want_run_btn.setObjectName("want_run_btn")
        self.verticalLayout.addWidget(self.want_run_btn, 0, QtCore.Qt.AlignHCenter)
        self.want_sponsor_btn = QtWidgets.QPushButton(self.greet_bg)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(
            self.want_sponsor_btn.sizePolicy().hasHeightForWidth()
        )
        self.want_sponsor_btn.setSizePolicy(sizePolicy)
        self.want_sponsor_btn.setMinimumSize(QtCore.QSize(300, 60))
        self.want_sponsor_btn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.want_sponsor_btn.setObjectName("want_sponsor_btn")
        self.verticalLayout.addWidget(self.want_sponsor_btn, 0, QtCore.Qt.AlignHCenter)
        self.want_info_btn = QtWidgets.QPushButton(self.greet_bg)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(
            self.want_info_btn.sizePolicy().hasHeightForWidth()
        )
        self.want_info_btn.setSizePolicy(sizePolicy)
        self.want_info_btn.setMinimumSize(QtCore.QSize(300, 60))
        self.want_info_btn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.want_info_btn.setObjectName("want_info_btn")
        self.verticalLayout.addWidget(self.want_info_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.login_btn = QtWidgets.QPushButton(self.greet_bg)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMinimumSize(QtCore.QSize(200, 40))
        self.login_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout_6.addWidget(self.login_btn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_7.addWidget(self.greet_bg)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.greet_time_left = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.greet_time_left.sizePolicy().hasHeightForWidth()
        )
        self.greet_time_left.setSizePolicy(sizePolicy)
        self.greet_time_left.setMinimumSize(QtCore.QSize(787, 10))
        self.greet_time_left.setMaximumSize(QtCore.QSize(16777215, 50))
        self.greet_time_left.setAlignment(QtCore.Qt.AlignCenter)
        self.greet_time_left.setObjectName("greet_time_left")
        self.verticalLayout_4.addWidget(self.greet_time_left)
        self.verticalLayout_7.addWidget(self.frame)
        self.greet_bg.raise_()
        self.frame_head.raise_()
        self.frame.raise_()
        UiGreetWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UiGreetWindow)
        QtCore.QMetaObject.connectSlotsByName(UiGreetWindow)

    def retranslateUi(self, UiGreetWindow):
        _translate = QtCore.QCoreApplication.translate
        UiGreetWindow.setWindowTitle(_translate("UiGreetWindow", "MainWindow"))
        self.greet_heading.setText(_translate("UiGreetWindow", "MARATHON SKILLS 2016"))
        self.greet_city_label.setText(_translate("UiGreetWindow", "Москва, Россия"))
        self.greet_date_label.setText(
            _translate("UiGreetWindow", "среда 21 октября 2016")
        )
        self.want_run_btn.setText(_translate("UiGreetWindow", "Я хочу стать бегуном"))
        self.want_sponsor_btn.setText(
            _translate("UiGreetWindow", "Я хочу стать спонсором")
        )
        self.want_info_btn.setText(
            _translate("UiGreetWindow", "Я хочу больше узнать о событии")
        )
        self.login_btn.setText(_translate("UiGreetWindow", "Login"))
        self.greet_time_left.setText(_translate("UiGreetWindow", "... до марафона "))


# if __name__ == "__main__":
#     import sys

#     app = QtWidgets.QApplication(sys.argv)
#     UiGreetWindow = QtWidgets.QMainWindow()
#     ui = Ui_UiGreetWindow()
#     ui.setupUi(UiGreetWindow)
#     UiGreetWindow.show()
#     sys.exit(app.exec_())
