# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\10_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 763)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    background-color: rgb(242, 242, 242);\n"
"    border: 2px solid;\n"
"    border-radius: 10px;\n"
"    \n"
"    border-color: rgb(140, 140, 140);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QFrame {\n"
"    background-color: rgb(82, 82, 82);\n"
"}\n"
"\n"
"\n"
"QLabel#heading{\n"
"    font-size: 24pt;\n"
"    background-color: rgb(82, 82, 82);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel#greet_city_label, QLabel#greet_date_label{\n"
"    font-size: 14pt;\n"
"    color: rgb(204, 204, 204);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"QFrame#frame_bg{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit {\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"border: 1px solid;\n"
"    border-color: rgb(127, 127, 127);\n"
"}\n"
"QComboBox{\n"
"border: 1px solid;\n"
"    border-color: rgb(127, 127, 127);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_bg = QtWidgets.QFrame(self.centralwidget)
        self.frame_bg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg.setObjectName("frame_bg")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_bg)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.header_frame = QtWidgets.QFrame(self.frame_bg)
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_btn = QtWidgets.QPushButton(self.header_frame)
        self.back_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.back_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        self.heading = QtWidgets.QLabel(self.header_frame)
        self.heading.setMaximumSize(QtCore.QSize(16777215, 40))
        self.heading.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.heading.setObjectName("heading")
        self.horizontalLayout.addWidget(self.heading)
        self.verticalLayout_8.addWidget(self.header_frame)
        self.window_content = QtWidgets.QVBoxLayout()
        self.window_content.setContentsMargins(10, 10, 10, 10)
        self.window_content.setSpacing(30)
        self.window_content.setObjectName("window_content")
        self.label = QtWidgets.QLabel(self.frame_bg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.window_content.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.info_btn = QtWidgets.QPushButton(self.frame_bg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_btn.sizePolicy().hasHeightForWidth())
        self.info_btn.setSizePolicy(sizePolicy)
        self.info_btn.setMinimumSize(QtCore.QSize(0, 90))
        self.info_btn.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.info_btn.setFont(font)
        self.info_btn.setObjectName("info_btn")
        self.gridLayout.addWidget(self.info_btn, 0, 0, 1, 1)
        self.what_long_btn = QtWidgets.QPushButton(self.frame_bg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.what_long_btn.sizePolicy().hasHeightForWidth())
        self.what_long_btn.setSizePolicy(sizePolicy)
        self.what_long_btn.setMinimumSize(QtCore.QSize(0, 90))
        self.what_long_btn.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.what_long_btn.setFont(font)
        self.what_long_btn.setStyleSheet("")
        self.what_long_btn.setObjectName("what_long_btn")
        self.gridLayout.addWidget(self.what_long_btn, 0, 2, 1, 1)
        self.past_res_btn = QtWidgets.QPushButton(self.frame_bg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.past_res_btn.sizePolicy().hasHeightForWidth())
        self.past_res_btn.setSizePolicy(sizePolicy)
        self.past_res_btn.setMinimumSize(QtCore.QSize(0, 90))
        self.past_res_btn.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.past_res_btn.setFont(font)
        self.past_res_btn.setObjectName("past_res_btn")
        self.gridLayout.addWidget(self.past_res_btn, 1, 0, 1, 1)
        self.open_org_list = QtWidgets.QPushButton(self.frame_bg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_org_list.sizePolicy().hasHeightForWidth())
        self.open_org_list.setSizePolicy(sizePolicy)
        self.open_org_list.setMinimumSize(QtCore.QSize(0, 90))
        self.open_org_list.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.open_org_list.setFont(font)
        self.open_org_list.setStyleSheet("")
        self.open_org_list.setFlat(False)
        self.open_org_list.setObjectName("open_org_list")
        self.gridLayout.addWidget(self.open_org_list, 1, 2, 1, 1)
        self.window_content.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.window_content.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.window_content)
        self.footer_frame = QtWidgets.QFrame(self.frame_bg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footer_frame.sizePolicy().hasHeightForWidth())
        self.footer_frame.setSizePolicy(sizePolicy)
        self.footer_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.footer_frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.greet_time_left = QtWidgets.QLabel(self.footer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greet_time_left.sizePolicy().hasHeightForWidth())
        self.greet_time_left.setSizePolicy(sizePolicy)
        self.greet_time_left.setStyleSheet("QLabel#greet_time_left{\n"
"    font-size: 12pt;\n"
"    color: #fff;\n"
"    background-color: rgba(242, 242, 242, 0);\n"
"}")
        self.greet_time_left.setAlignment(QtCore.Qt.AlignCenter)
        self.greet_time_left.setObjectName("greet_time_left")
        self.verticalLayout_7.addWidget(self.greet_time_left)
        self.verticalLayout_8.addWidget(self.footer_frame)
        self.verticalLayout_3.addWidget(self.frame_bg)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_btn.setText(_translate("MainWindow", "Назад"))
        self.heading.setText(_translate("MainWindow", "Мarathone SKILLS 2016"))
        self.label.setText(_translate("MainWindow", "Подробная информация"))
        self.info_btn.setText(_translate("MainWindow", "Maraphone 2016"))
        self.what_long_btn.setText(_translate("MainWindow", "Насколько долгий марафон"))
        self.past_res_btn.setText(_translate("MainWindow", "Предыдущие результаты"))
        self.open_org_list.setText(_translate("MainWindow", "Список благотворительных организаций "))
        self.greet_time_left.setText(_translate("MainWindow", "... до марафона "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
